name: WorkFlow - Tech Challenge F2
on:  
  # Dispara o workflow quando realizar push na branch master
  push:
    branches: [ "master" ]
jobs:
  job01:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest  
    steps:      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:            
          username: 'jorgeoliveira'        
          password: ${{ secrets.SECRET}}

      - name: Build and push Docker images  
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'jorgeoliveira/fiap-githubactions:latest'
          push: true
          

          
    
          




      
          
