name: WorkFlow - Tech Challenge F2
on:  
  # Dispara o workflow quando realizar push na branch master
  push:
    branches: [ "master" ]
jobs:
  job01:
    name: Job para gerar o build, gerar imagem e publicar imagem no Docker Hub.
    runs-on: ubuntu-latest  
    steps:   
      - name: Realiza Checkout do código fonte
        uses: actions/checkout@v3
        
      - name: Realiza o Login no Docker Hub
        uses: docker/login-action@v3.0.0
        with:            
          username: 'jorgeoliveira'        
          password: ${{ secrets.SECRET}}

      - name: Build e Push da Imagem Docker para o Docker Hub
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'jorgeoliveira/fiap-githubactions:latest'
          push: true
          

          
    
          




      
          
